// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqb1IyqFS2Lr55XRGLNrffklGC0YKr_k',
    appId: '1:435030485646:android:ac0899efee426ce84b37df',
    messagingSenderId: '435030485646',
    projectId: 'chat-app-1fcc6',
    storageBucket: 'chat-app-1fcc6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYI5dx7KUSbXtEOoBIBTzshULaMAIXvFY',
    appId: '1:435030485646:web:ecc8e0c48abc9de84b37df',
    messagingSenderId: '435030485646',
    projectId: 'chat-app-1fcc6',
    authDomain: 'chat-app-1fcc6.firebaseapp.com',
    storageBucket: 'chat-app-1fcc6.firebasestorage.app',
    measurementId: 'G-MP5JTK1YJS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSC3Q22WK1GrpE8Rs-xjcWY0gS1oHXPjE',
    appId: '1:435030485646:ios:6583bd6e163d0f5b4b37df',
    messagingSenderId: '435030485646',
    projectId: 'chat-app-1fcc6',
    storageBucket: 'chat-app-1fcc6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}